/*
 * This source file was generated by the Gradle 'init' task
 */
package me.serenitycodes;

public class SchedulerMain {
  public static String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(getGreeting());
  }
}
