version: "3.9"
services:
  productivity-agi:
    build:
      context: .
      dockerfile: Dockerfile
    devices:
    - /dev/snd
    volumes:
      - ./db:/app/db
      - ./data:/data
    env_file:
      - .env
